all: list_graph matrix_graph set_graph arc_graph

list_graph: list_graph.h list_graph.cpp
	clang++ -std=c++17 -O2 -c list_graph.cpp

matrix_graph: matrix_graph.h matrix_graph.cpp
	clang++ -std=c++17 -O2 -c matrix_graph.cpp

set_graph: set_graph.h set_graph.cpp
	clang++ -std=c++17 -O2 -c set_graph.cpp

arc_graph: arc_graph.h arc_graph.cpp
	clang++ -std=c++17 -O2 -c arc_graph.cpp
